server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: person-service
          uri: lb://person-service
          predicates:
            - Path=/persons/**
        - id: family-service
          uri: lb://family-service
          predicates:
            - Path=/families/**
        - id: tree-service
          uri: lb://tree-service
          predicates:
            - Path=/trees/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
