server:
  port: 8084

spring:
  application:
    name: tree-service
  datasource:
    url: jdbc:postgresql://localhost:5432/familytree_tree
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
